alias clear 'command clear; echo; echo; seq 1 (tput cols) | sort -R | spark; echo; echo'
alias emacs 'env TERM=xterm-direct emacs'
alias todo-edit 'editor ~/todo.txt'
alias l 'ls -CF'
alias la 'ls -A'
alias ll 'ls -alF'
